platform :ios, '12.0'

target 'Runner' do
  use_frameworks!

  # Comment the next line if you don't want to use dynamic frameworks
  # Adjust settings for simulator builds
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      end
    end
  end
end

